### ISSUE TITLE
Client timed out while executing (no jobFinished received)

### ISSUE THREAD

**Issue by bazted** [evant/JobSchedulerCompat#14]
Hi,

First of all thanks for great compat library.

But I have an issue with long running operations.

I am scheduling a job
```Java
 JobInfo job = new JobInfo.Builder(taskId++,
                jobService)
                .setExtras(extras)
                .setRequiredNetworkType(JobInfo.NETWORK_TYPE_ANY)
                .setPersisted(true)
                .setOverrideDeadline(12000000)
                .build();
        jobScheduler.schedule(job);
```

And I have an JobService with AndroidAnnotations:
```Java
public class UploadImageJobService extends JobService {

       private final SparseArrayCompat<JobParameters> jobParamsMap = new SparseArrayCompat<>();

    @Override
    public boolean onStartJob(JobParameters jobParameters) {
        // extracting params and uploading large image
            jobParamsMap.put(jobParameters.getJobId(), jobParameters);
            uploadImage(params);
            return true;
     }
   @Background
   void uploadImage(){
   //uploading image using Retrofit
   if(success)  jobFinished(jobParamsMap.get(jobId), false);
   }
    @Override
    public boolean onStopJob(JobParameters jobParameters) {
        //checking if image is sent 
        if (imageSent) {
            return false;
        }
        sendActionLog("onStopJob",
                    jobParameters.getJobId(), "sending not finished retry");
        return true;
    }
}
```

Uploading begins when there is internet connection but after some time Service just receives onStopJob()
logs:
```
01-11 13:58:14.756      554-554/? I/JobServiceContext﹕ Client timed out while executing (no jobFinished received). sending onStop. test.UploadImageJobService_ jId=0, u0
01-11 13:58:14.773  11487-11542/test E/UploadImageJobService﹕ job=0 | exam=1981 [onStopJob] PersistableBundle[{Id=1981}]
```

even if I call
```Java
 .setOverrideDeadline(12000000)
```

Is it a bug or am I doing smth wrong? 

How can I force JobServiceContext to wait until I call jobFinished()? 

Thanks.

**Comment by evant** [comment]
Is this on Lollipop or below? "Client timed out" looks like Lollipop since job timeout is not yet implemented for the compat version. How long is your background task taking? There is a built-in limit of 60 seconds before JobScheduler considers your job as timed-out and stops it.

**Comment by bazted** [comment]
This was tested on Lollipop Nexus 4. 
Sometimes uploading large image taxes even 10 minutes.
But I moved this long running operation to other service and schedule job with checking database list.

**Comment by evant** [comment]
Well, that's your problem then. Google really should put the 60 second limit in their documentation, I only found it by looking through the source.
