### ISSUE TITLE
.setPeriodic does not work?

### ISSUE THREAD

**Issue by xbroak** [evant/JobSchedulerCompat#21]
It seems to only run once. No matter the value. The task will run, and then never run again

JobScheduler jobScheduler = JobScheduler.getInstance(getActivity());
            JobInfo job = new JobInfo.Builder(0 , new ComponentName(getActivity(), StartQuestionnaireTask.class))
                    .setPeriodic(1000)
                    .build();
            jobScheduler.schedule(job);

The task just opens a toast

**Comment by martin90s** [comment]
how to fix?
