### ISSUE TITLE
a Good project,why [Deprecated]? hope Continue to maintain and update...

### ISSUE THREAD

**Issue by xiaomeixw** [evant/JobSchedulerCompat#34]
RT...hope Continue to maintain and update...

**Comment by evant** [comment]
1) I don't have the time or interest to work on it. By it's nature it's _very_ hard to test if it's working correctly.
2) Google came out with a better solution with [Network Manager](https://developers.google.com/cloud-messaging/network-manager). It uses play services so jobs can be managed between apps far better.

If anyone else wants to fork and maintain this, feel free. Just note that a significant amount of work needs to be done to make this production ready.

**Comment by xiaomeixw** [comment]
@evant Thanks,I read the article "Implementing GCM Network Manager on Android" ,It‘a good solution...Thanks for your hard work...can close the issue...
